### PR TITLE
[LOGIN SCENE] Remember password

### PR DESCRIPTION
**Pull request by xinsodev**
As a player, I don't want to re-enter my password every time I go to the login screen.

- [ v ] Add a checkbox "Remember me" below the password input.
- [ v ] Save the password when the checkbox is selected, and the player click login button.
- [ v ] Encrypt the password before saving (use DPAPI).

### CODE REVIEW

**Comment by xinsodev** [comment]
Hi @sven-n
If possible, please help me improve password encryption.
Thanks.

**Comment by sven-n** [comment]
Thanks, Looks fine 👍
You could try to use the DPAPI instead of using AES.

https://learn.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata

**Comment by xinsodev** [comment]
> Thanks, Looks fine 👍 You could try to use the DPAPI instead of using AES.
> 
> https://learn.microsoft.com/en-us/windows/win32/api/dpapi/nf-dpapi-cryptprotectdata

I used DPAPI for data protection.
Thank for your guide.

**Comment by sven-n** [comment]
Thanks :)

**Pull request merged**
